CI/CD

diff --git a/.github/workflows/chatbot_deploy.yml b/.github/workflows/chatbot_deploy.yml
--- a/.github/workflows/chatbot_deploy.yml
+++ b/.github/workflows/chatbot_deploy.yml
@@ -46,10 +46,6 @@ jobs:
         echo "FRONDEND IP: $EC2_IP"
         echo "EC2_PUBLIC_IP=$EC2_IP" >> "$GITHUB_ENV"
 
-    - name: Sử dụng EC2_PUBLIC_IP
-      run: |
-        echo "ENV: ${{ env.EC2_PUBLIC_IP }}"
-
     - name: Pull & Run Image chatbot_frontend from DockerHub in EC2
       run: |
         ssh -o StrictHostKeyChecking=no -i keypair.pem ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
@@ -96,65 +92,83 @@ jobs:
 
         sudo docker run -d -p 9200:9200 -d --name elasticsearch -e "discovery.type=single-node" -e "xpack.security.enabled=false" -e "xpack.license.self_generated.type=trial" -v "elasticsearch-data:/usr/share/elasticsearch/data" docker.elastic.co/elasticsearch/elasticsearch:8.15.0
 
-        INNER_EOF
-        EOF
-      
-    - name: Set Neo4j IP is GITHUB_ENV -> NEO4J_IP
-      run: |
-        cd iac_using_terraform
-        EC2_IP=$(terraform output -raw elasticsearch_private_ip | cut -d ':' -f1 | tr -d '\r\n' | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
-        echo "Neo4j IP: $EC2_IP"
-        echo "NEO4J_IP=$EC2_IP" >> "$GITHUB_ENV"
-      
-    - name: Pull & Run Image Neo4j in EC2
-      run: |
-        echo "EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}"
-        echo "NEO4J_IP: ${{ env.NEO4J_IP }}"
-
-        ssh -o StrictHostKeyChecking=no -i keypair.pem ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
-
-        ssh -o StrictHostKeyChecking=no -i ~/keypair.pem ubuntu@${{ env.NEO4J_IP }} << 'INNER_EOF'
-      
-        if ! command -v docker &> /dev/null; then
-          sudo apt update && sudo apt upgrade -y
-          sudo apt install docker.io -y
-          sudo systemctl start docker
-          sudo systemctl enable docker
+        sudo apt install -y python3-pip python3.12-venv git
+        if [ -d "chatbot_elasticsearch_data/.git" ]; then
+          echo "📁 Repo already exists. Pulling latest changes..."
+          cd chatbot_elasticsearch_data
+          git pull
+        else
+          echo "📁 Repo not found. Cloning..."
+          git clone https://github.com/quynhbuiofficial/chatbot_elasticsearch_data.git
+          cd chatbot_elasticsearch_data
         fi
+        python3 -m venv .venv
+        source .venv/bin/activate
+        pip install uv
+        uv pip install -r requirements.txt
 
-        sudo docker run -d --name neo4j-apoc -p 7474:7474 -p 7687:7687 -e "NEO4J_AUTH=neo4j/123456789" -e "NEO4J_PLUGINS=[\"apoc\"]" -e "NEO4J_apoc_export_file_enabled=true" -e "NEO4J_apoc_import_file_enabled=true" -e "NEO4J_apoc_import_file_use__neo4j__config=true" -e "NEO4J_dbms_security_procedures_unrestricted=apoc.*" -e "NEO4J_dbms_security_procedures_allowlist=apoc.*" -v neo4j_data:/data -v neo4j_logs:/logs neo4j:2025.04
-
+        python3 index_data_tma.py
+        python3 index_data_law.py
+        
         INNER_EOF
         EOF
       
-    - name: Set Mcp_server IP is GITHUB_ENV -> MCP_IP
-      run: |
-        cd iac_using_terraform
-        EC2_IP=$(terraform output -raw elasticsearch_private_ip | cut -d ':' -f1 | tr -d '\r\n' | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
-        echo "MCP IP: $EC2_IP"
-        echo "MCP_IP=$EC2_IP" >> "$GITHUB_ENV"
-    
-    - name: Pull & Run Image Mcp_server from DockerHub in EC2
-      run: |
-        echo "EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}"
-        echo "NEO4J_IP: ${{ env.NEO4J_IP }}"
-
-        ssh -o StrictHostKeyChecking=no -i keypair.pem ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
-
-        ssh -o StrictHostKeyChecking=no -i ~/keypair.pem ubuntu@${{ env.NEO4J_IP }} << 'INNER_EOF'
+    # - name: Set Neo4j IP is GITHUB_ENV -> NEO4J_IP
+    #   run: |
+    #     cd iac_using_terraform
+    #     EC2_IP=$(terraform output -raw elasticsearch_private_ip | cut -d ':' -f1 | tr -d '\r\n' | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
+    #     echo "Neo4j IP: $EC2_IP"
+    #     echo "NEO4J_IP=$EC2_IP" >> "$GITHUB_ENV"
       
-        if ! command -v docker &> /dev/null; then
-          sudo apt update && sudo apt upgrade -y
-          sudo apt install docker.io -y
-          sudo systemctl start docker
-          sudo systemctl enable docker
-        fi
+    # - name: Pull & Run Image Neo4j in EC2
+    #   run: |
+    #     echo "EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}"
+    #     echo "NEO4J_IP: ${{ env.NEO4J_IP }}"
 
-        sudo docker pull quynhsydaole/mcp_server:latest
+    #     ssh -o StrictHostKeyChecking=no -i keypair.pem ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
 
-        sudo docker rm -f mcp_server || true
+    #     ssh -o StrictHostKeyChecking=no -i ~/keypair.pem ubuntu@${{ env.NEO4J_IP }} << 'INNER_EOF'
+      
+    #     if ! command -v docker &> /dev/null; then
+    #       sudo apt update && sudo apt upgrade -y
+    #       sudo apt install docker.io -y
+    #       sudo systemctl start docker
+    #       sudo systemctl enable docker
+    #     fi
+
+    #     sudo docker run -d --name neo4j-apoc -p 7474:7474 -p 7687:7687 -e "NEO4J_AUTH=neo4j/123456789" -e "NEO4J_PLUGINS=[\"apoc\"]" -e "NEO4J_apoc_export_file_enabled=true" -e "NEO4J_apoc_import_file_enabled=true" -e "NEO4J_apoc_import_file_use__neo4j__config=true" -e "NEO4J_dbms_security_procedures_unrestricted=apoc.*" -e "NEO4J_dbms_security_procedures_allowlist=apoc.*" -v neo4j_data:/data -v neo4j_logs:/logs neo4j:2025.04
+
+    #     INNER_EOF
+    #     EOF
+      
+    # - name: Set Mcp_server IP is GITHUB_ENV -> MCP_IP
+    #   run: |
+    #     cd iac_using_terraform
+    #     EC2_IP=$(terraform output -raw elasticsearch_private_ip | cut -d ':' -f1 | tr -d '\r\n' | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
+    #     echo "MCP IP: $EC2_IP"
+    #     echo "MCP_IP=$EC2_IP" >> "$GITHUB_ENV"
     
-        sudo docker run -d --name mcp_server -p 1234:1234 -e ELASTICSEARCH_URL=${{ env.ELASTICSEARCH_IP }} quynhsydaole/mcp_server:v1.0
+    # - name: Pull & Run Image Mcp_server from DockerHub in EC2
+    #   run: |
+    #     echo "EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}"
+    #     echo "NEO4J_IP: ${{ env.NEO4J_IP }}"
 
-        INNER_EOF
-        EOF
+    #     ssh -o StrictHostKeyChecking=no -i keypair.pem ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
+
+    #     ssh -o StrictHostKeyChecking=no -i ~/keypair.pem ubuntu@${{ env.NEO4J_IP }} << 'INNER_EOF'
+      
+    #     if ! command -v docker &> /dev/null; then
+    #       sudo apt update && sudo apt upgrade -y
+    #       sudo apt install docker.io -y
+    #       sudo systemctl start docker
+    #       sudo systemctl enable docker
+    #     fi
+
+    #     sudo docker pull quynhsydaole/mcp_server:latest
+
+    #     sudo docker rm -f mcp_server || true
+    
+    #     sudo docker run -d --name mcp_server -p 1234:1234 -e ELASTICSEARCH_URL=${{ env.ELASTICSEARCH_IP }} quynhsydaole/mcp_server:v1.0
+
+    #     INNER_EOF
+    #     EOF
